### PR TITLE
Fixed a few bugs, mostly ensuring correct handing UTF-8 with MySQL

### LINKED ISSUE #264: Install without php-ctype is not checked
During install, some checks are made, and it's probably a good idea to check if php-ctype is available.

At present, after everything is shown "OK" (database_setup page) there is an error if php-ctype is not enabled

An uncaught Exception was encountered
Type: Error
Message: Call to undefined function ctype_digit()
Filename: /var/www/vendor/codeigniter/framework/system/database/DB_driver.php
Line Number: 1399

### LINKED ISSUE #265: compose_process with some unicode chars fails (db error) - eg. 😍
**/messages/compose_process** returns 500

A Database Error Occurred
Error Number: 1366

Incorrect string value: '\xF0\x9F\x98\x8D' for column `kalkun`.`outbox`.`TextDecoded` at row 1

INSERT INTO `outbox` (`InsertIntoDB`, `SendingDateTime`, `DestinationNumber`, `Coding`, `Class`, `CreatorID`, `SenderID`, `TextDecoded`, `RelativeValidity`, `DeliveryReport`) VALUES ('2021-05-14 03:04:12', '2021-05-14 03:04:12', '1234567890', 'Unicode_No_Compression', '1', '', NULL, 'Goodbye 😍', '-1', 'default')

Filename: models/gateway/Gammu_model.php

Line Number: 202

### PR DESCRIPTION
**Pull request by realJoshByrnes**
- Added Kalkun signature to Gammu database when composing new messages
- Increased minimum MySQL version to 5.5.3
- Added full UTF-8 support in MySQL database and config - fixes #265
- Added PHP-Ctype detection on Installation - fixes #264
- Reset default password to ‘kalkun’
- MySQL upgrade now specifies the same character encoding as MySQL dump

### CODE REVIEW

File: application/config/database.php [hunk 1]
```diff
@@ -60,8 +60,15 @@
...
-$db['default']['char_set'] = "utf8";
-$db['default']['dbcollat'] = "utf8_general_ci";
+
+if ($db['default']['dbdriver'] == "mysqli") {
+	$db['default']['char_set'] = "utf8mb4";
+	$db['default']['dbcollat'] = "utf8mb4_general_ci";
+}
+else {
+	$db['default']['char_set'] = "utf8";
+  $db['default']['dbcollat'] = "utf8_general_ci";
```
Comment (tenzap) [inline application/config/database.php:70]: As per ci3 doc, dbcollat is Only used in the ‘mysql’ and ‘mysqli’ drivers
https://codeigniter.com/userguide3/database/configuration.html?highlight=database#explanation-of-values

Comment (realJoshByrnes) [reply application/config/database.php]: dbcollat has been set by @back2arie for ~10 years for all db types (see [blame for current database.php](https://github.com/back2arie/Kalkun/blame/00e9ec16e27f8dfff553e768b9a0e593771114ed/application/config/database.php#L64)

@tenzap I've updated the code so that it's a little more obvious that dbcollat should only be used with the MySQL(i) driver.

File: media/db/mysql_kalkun.sql [hunk 2]
```diff
@@ -60,14 +60,14 @@ CREATE TABLE IF NOT EXISTS `user` (
...
-)  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;
+)  DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=2 ;
 
 --
 -- Dumping data for table `user`
 --
 
 INSERT INTO `user` (`id_user`, `username`, `realname`, `password`, `phone_number`, `level`) VALUES
-(1, 'kalkun', 'Kalkun SMS', '$2y$10$Sg0IxngRIIp1qNITM8kWa.aJ26w58F97ByTzDKoRF/dyzKcLfx226', '123456789', 'admin');
+(1, 'kalkun', 'Kalkun SMS', '$2y$10$sIXe0JiaTIOsC7OOnox5t.deuJwZoawd5QKpQlSNfywziTDHpmmyy', '123456789', 'admin');
```
Comment (kingster) [inline media/db/mysql_kalkun.sql:70]: Is the default password being updated here?
